package mx.fca.listas;

public class Contactos {

    public static String [] all = {
            "Cristian Cardoso",
            "Fernando Perez",
            "Kenia Martinez",
            "La bebesita",
            "Cristian Cardoso",
            "Fernando Perez",
            "Kenia Martinez",
            "La bebesita",
            "Cristian Cardoso",
            "Fernando Perez",
            "Kenia Martinez",
            "La bebesita",
            "Cristian Cardoso",
            "Fernando Perez",
            "Kenia Martinez",
            "La bebesita",
            "Cristian Cardoso",
            "Fernando Perez",
            "Kenia Martinez",
            "La bebesita",
            "Cristian Cardoso",
            "Fernando Perez",
            "Kenia Martinez",
            "La bebesita",
            "Cristian Cardoso",
            "Fernando Perez",
            "Kenia Martinez",
            "La bebesita",
            "Cristian Cardoso",
            "Fernando Perez",
            "Kenia Martinez",
            "La bebesita",
            "Cristian Cardoso",
            "Fernando Perez",
            "Kenia Martinez",
            "La bebesita",
            "Cristian Cardoso",
            "Fernando Perez",
            "Kenia Martinez",
            "La bebesita",
            "Cristian Cardoso",
            "Fernando Perez",
            "Kenia Martinez",
            "La bebesita",
            "Cristian Cardoso",
            "Fernando Perez",
            "Kenia Martinez",
            "La bebesita"

    };
}
